// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Server.Models;

namespace Project.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Project.Shared.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateOfBirth = new DateTime(1980, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@pragimtech.com",
                            Name = "John",
                            PhoneNumber = "6909 - 555 - 0175",
                            Sid = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateOfBirth = new DateTime(1981, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sam@pragimtech.com",
                            Name = "Sam",
                            PhoneNumber = "6909 - 555 - 0175",
                            Sid = 2
                        },
                        new
                        {
                            EmployeeId = 3,
                            DateOfBirth = new DateTime(1979, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mary@pragimtech.com",
                            Name = "Mary",
                            PhoneNumber = "6909 - 555 - 0175",
                            Sid = 3
                        },
                        new
                        {
                            EmployeeId = 4,
                            DateOfBirth = new DateTime(1982, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@pragimtech.com",
                            Name = "Sara",
                            PhoneNumber = "6909 - 555 - 0175",
                            Sid = 4
                        });
                });

            modelBuilder.Entity("Project.Shared.Status", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("InvoiceStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sid");

                    b.ToTable("Statuse");

                    b.HasData(
                        new
                        {
                            Sid = 1,
                            InvoiceStatus = "Active"
                        },
                        new
                        {
                            Sid = 2,
                            InvoiceStatus = "Inactive"
                        },
                        new
                        {
                            Sid = 3,
                            InvoiceStatus = "Hold"
                        },
                        new
                        {
                            Sid = 4,
                            InvoiceStatus = "InProgress"
                        },
                        new
                        {
                            Sid = 5,
                            InvoiceStatus = "Complete"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
